### ISSUE TITLE
[1.19.2]与机械动力单测冲突

### ISSUE THREAD

**Issue by WinterArch** [wzsjc2020/Minecraft-Comfy-Sky-Mod#1]
[minecraft-exported-logs-2023-05-14T11-22-23.log](https://github.com/wzsjc2020/Minecraft-Comfy-Sky-Mod/files/11471038/minecraft-exported-logs-2023-05-14T11-22-23.log)

1.19.2fabric单测机械动力和舒适空岛出现冲突，log在这，希望在1.19.2解决冲突。机械空岛是好文明。

**Comment by wzsjc2020** [comment]
这个冲突是由于 com.wzssoft.comfysky.mixin.GlassBottleItemMixin的问题和机械动力的牛奶产生了冲突
这个兼容性问题已于ComfySky-1.19.2-17.1.1+fix-1中被修复
同时还修复了机械动力API导致挖掘铲破坏方块异常的问题
